### ISSUE TITLE
Returned data different in Chrome and Firefox

### ISSUE THREAD

**Issue by klabarge** [qzind/sift#7] opened 2017-01-12 04:53 UTC
Note I have not tested in any other browser except Chrome and Firefox

**OS:** Windows 10
**Sift Version:** from PR https://github.com/qzind/sift/pull/4

I am using the `burnedIn` filtering

Using the below code (I am using QZ Tray qz.networking.devices() ) the returned data is vastly different in Chrome and Firefox

```js
function listNetworkDevices() {

    qz.networking.devices().then(function(data) {
    data = sift.keep(data, {burnedIn: true});
    console.log('after sift!!');
    console.log(data);
    }).catch(function(e) { console.error(e); });
}
```

### Firefox
* When I run the above code in Firefox, there are 6 returned items

  ![image](https://cloud.githubusercontent.com/assets/12505463/21877095/a565bb86-d856-11e6-95a4-b8b97c2f106a.png)

  ![image](https://cloud.githubusercontent.com/assets/12505463/21877105/bb6a8fce-d856-11e6-8a90-22d0dff3a909.png)

* There are 60 adapters returned when I switch to `sift.toss`

  ![image](https://cloud.githubusercontent.com/assets/12505463/21877323/46c1efa8-d858-11e6-906d-665b8bee646a.png)

### Chrome

* When I run this code in Chrome, there are 62 returned objects.

  At first glance this appears that the inverse is happening, but I noticed they both returned the *VirtualBox NDIS 6.0 Miniport Driver*

  ![image](https://cloud.githubusercontent.com/assets/12505463/21877204/5c5336ac-d857-11e6-8ee7-500ea9060237.png)

* There are 4 adapters returned when I change to `sift.toss`:

  ![image](https://cloud.githubusercontent.com/assets/12505463/21877280/ddfd87f2-d857-11e6-9a16-15ac239b394d.png)

**Side Note:** In Chrome only, it appears that additional information is logged to the console before the `console.log();`'s that I have in the code snippet above.  It appears that each adapter is logged to the console (regardless of `sift.toss` or `sift.keep`)

![image](https://cloud.githubusercontent.com/assets/12505463/21877432/1111c83c-d859-11e6-9355-0a1a67651279.png)

**Comment by tresf** [comment] 2017-01-20 03:05
Cannot reproduce.   I'm getting identical results between Firefox and Chrome.

Can you post the exact code you're using?  Here's my unit tests.  Side note... I'm not too happy about the `... Virtual ...` adapters which use physical addresses, but that's a topic for another discussion.

Using https://raw.githubusercontent.com/qzind/sift/issue-4/sift.js

```html
<html>
<script src="sift.js"></script>
<script>
var data = [
	{
		id: "eth0",
		ip: "fe80:0:0:0:413d:d51d:41f3:de1b",
		ip4: [ "192.168.1.1" ],
		ip6: [ "fe80:0:0:0:413d:d51d:41f3:de1b" ],
		mac: "0A002700002",
		name: "VirtualBox NDIS 6.0 Miniport Driver",
		primary: false,
		up: true,
	},
	{
		id: "eth2",
		ip: "fe80:0:0:0:df9:6916:c7fd:c0f7",
		ip6: [ "fe80:0:0:0:df9:6916:c7fd:c0f7" ],
		mac: "F0761CD89C27",
		name: "Realtek PCIe GBE Family Controller",
		primary: false,
		up: true
	},
	{
		id: "wlan0",
		ip: "fe80:0:0:0:c400:4e4b:f563:316f",
		ip4: [ "192.168.1.2" ],
		ip6: [ "fe80:0:0:0:c400:4e4b:f563:316f" ],
		mac: "F0761CD89C27",
		name: "Intel(R) Dual Band Wireless-AC 3160",
		primary: true,
		up: true
	},
	{
		id: "eth3",
		ip: "fe80:0:0:0:5c42:8db0:dd26:5923",
		ip6: [ "fe80:0:0:0:5c42:8db0:dd26:5923" ],
		mac: "E4F89C5B247F",
		name: "Bluetooth PAN HelpText",
		primary: false,
		up: false
	},
	{
		id: "wlan1",
		ip: "fe80:0:0:0:1444:e887:58e9:7db9",
		ip6: [ "fe80:0:0:0:1444:e887:58e9:7db9" ],
		mac: "E4F89C5B247C",
		name: "Microsoft Wi-Fi Direct Virtual Adapter",
		primary: false,
		up: false
	},
	{
		id: "wlan2",
		ip: "fe80:0:0:0:1c6a:40c9:b4e2:c534",
		ip6: [ "fe80:0:0:0:1c6a:40c9:b4e2:c534" ],
		mac: "E6F89C5B247B",
		name: "Microsoft Hosted Network Virtual Adapter",
		primary: false,
		up: false
	},
	{
		id: "eth0",
		ip: "fe80:0:0:0:413d:d51d:41f3:de1b",
		ip4: [ "192.168.1.1" ],
		ip6: [ "fe80:0:0:0:413d:d51d:41f3:de1b" ],
		mac: "0A002700002",
		name: "VirtualBox NDIS 6.0 Miniport Driver",
		primary: false,
		up: true,
	},
	{
		ip: "0:0:0:0:0:0:1",
		ip4: [ "127.0.0.1" ],
		ip6: [ "0:0:0:0:0:0:1" ],
		name: "Software Loopback Interface 1",
		primary: false,
		up: true,
	},
	{
		name: "WAN Miniport (Network Monitor)",
		primary: false,
		up: false,
	},
	{
		name: "Bluetooth Device (RFCOMM Protocol TDI)",
		primary: false,
		up: false,
	},
	{
		name: "Microsoft ISATAP Adapter #6",
		primary: false,
		up: false,
	},
	{
		name: "WAN Miniport (L2TP)",
		primary: false,
		up: false,
	},
	{
		id: "net4",
		ip: "fe80:0:0:0:0:5efe:c0a8:3801",
		ip6: [ "fe80:0:0:0:0:5efe:c0a8:3801" ],
		mac: "00000000000000E0",
		name: "Microsoft ISATAP Adapter",
		primary: false,
		up: false,
	},
	{
		id: "net7",
		ip: "fe80:0:0:0:0:ffff:ffff:fffe",
		ip6: [ "fe80:0:0:0:0:ffff:ffff:fffe" ],
		mac: "00000000000000E0",
		name: "Microsoft Teredo Tunneling Adapter",
		primary: false,
		up: false,
	},
	{
		id: "net11",
		ip: "fe80:0:0:0:0:5efe:a0a:a68",
		ip6: [ "fe80:0:0:0:0:5efe:a0a:a68" ],
		mac: "00000000000000E0",
		name: "Microsoft ISATAP Adapter #3",
		primary: false,
		up: false,
	}
];
console.log("##### BEFORE #####");
console.log(data);

data = sift.toss(data, { burnedIn: false });

console.log("##### AFTER #####");
console.log(data);
</script>

```

**Comment by tresf** [comment] 2017-01-20 03:27
Per @klabarge this is not reproducible in his environment either.  Closing as invalid; merging `issue-4` branch.

**Closed as completed by tresf** 2017-01-20 03:27 UTC
Labels: invalid
